apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-deployment.yaml
- api-service.yaml
- embed-deployment.yaml
- embed-service.yaml
- redis-deployment.yaml
- web-deployment.yaml
- web-service.yaml
- widget-deployment.yaml
- widget-service.yaml
- ws-deployment.yaml
- ws-service.yaml

# namespace
# Adds namespace to all resources.
namespace: novu

nameSuffix: -dev

namePrefix: novu-

commonLabels:
  owner: novu

configMapGenerator:
- envs:
  - env-dev
  name: novu-env
